### ISSUE TITLE
https://dailycred.com/oauth/logout returns a 404

### ISSUE THREAD

**Issue by troygoode** [dailycred/passport-dailycred#1]

**Comment by hstove** [comment]
Hey Troy!

How exactly are you intending to use the `oauth/logout` route? It really isn't intended for use except for internally. All it does is clear your Dailycred tracking cookies, but it doesn't actually log you out, as we have no concept of 'remember me' on our side of the system. It is up to you to handle sessions and logging out on your site.

If you have any questions about implementing this or how you should handle it, feel free to ask on here or email me at hanks@dailycred.com, I'd love to help.

Hank

**Comment by troygoode** [comment]
The docs at https://www.dailycred.com/docs/node say to call it:

``` javascript
// Make sure you also let DailyCred know that your user has logged out:
app.get('/logout', function(req, res){
  req.logout();
  res.redirect('https://dailycred.com/oauth/logout?redirect_uri=http://localhost:3000/&client='+DAILYCRED_CLIENT_ID);
});
```

**Comment by hstove** [comment]
Sorry about that. The documentation was out of date. The current documentation on Dailycred.com has been fixed
