### ISSUE TITLE
Choice of SignIN or SignUP dailycred credentials page

### ISSUE THREAD

**Issue by jonesd** [dailycred/passport-dailycred#3]
Based upon the passport-dailycred example I can SignUP/SignIN to dailycred using passport from an express3 based website.

The inconvenience that I've experienced is that the dailycred.com credentials page triggered by passport-dailycred defaults to Sign UP. Most of the time my users want to Sign IN. If a user already has an account  then SignUP it will act as Sign IN, even without using the toggling feature of the credentials page, however, if you mistype your email address then you actually SignUP a new account with a misspelling rather than SignIN to an existing account.  The end result is redundant accounts and confused users.

Is it possible to configure passport.authenticate(...) on a per-call as to whether the dailycred.com credentials page default to SignIN or  SignUP mode?

I noticed that the dailycred documentation page https://www.dailycred.com/docs/serverside suggests an "action=signin" query param but that is for /connect rather than /oauth/authorize used by passport-dailycred.

Thanks, David Jones

**Comment by hstove** [comment]
Thanks for the bug report, this was much needed. You can now do this like so:

```
app.get('/auth/signin', passport.authenticate('dailycred', {action:'signin'}));
```

You can also use custom parameters `action`,`identity_provider`,and `access_token`.

The readme has been updated, and the documentation on dailycred.com will be updated soon as well.

Thanks for reaching out!
